var patient={
age:15 ,
scopedate: new Date(0),
polyps: false,
num_polyps: 0,
size_polyp: 0,
lnpcp: false,
hgd:false,
high_risk_polyp:false,
due_int_polyps: 100,
crc: false,
crc_resected: new Date(0),
loc_resect:false,
due_int_crc: 100,
fh_crc:false,
fh_risk:0,
lynch:false,
msh6_pmns:false,
sps:false,
fdr_sps:false,
mcra:false,
mcra_numb:0,
fap:false,
mutyh:false,
pjs:false,
jps:false,
due_interval_gen:100,
};